# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---
- name: Recreate required output directories
  tags: [eos_cli_config_gen]
  delegate_to: localhost
  run_once: true
  block:
    - name: "Cleanup {{ role_documentation_dir }}/tables"
      ansible.builtin.file:
        path: "{{ role_documentation_dir }}/tables"
        state: absent
    - name: "Create {{ role_documentation_dir }}/tables"
      ansible.builtin.file:
        path: "{{ role_documentation_dir }}/tables"
        state: directory
        mode: 0775

- name: Output eos_cli_config_gen Documentation
  tags: [eos_cli_config_gen]
  arista.avd.batch_template:
    template: "{{ role_path }}/../../docs/templates/avd_schema_table.j2"
    dest_format_str: "{{ role_documentation_dir ~ '/tables/{item}' ~ '.md'  }}"
    items: "{{ documentation_schema | list }}"
  vars:
    documentation_schema: "{{ role_name | arista.avd.convert_schema(type='documentation_tables') }}"
