---
- name: Validate states on EOS devices
  hosts: MEDIA_FABRIC
  connection: httpapi
  gather_facts: false

  tasks:
    - name: Validate states on EOS devices
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
