---
# Common AVD group variables

fabric_name: PTP_TESTS

mgmt_gateway: 192.168.0.1

# P2P links between leaf switches, connecting to the PTP Grandmaster.
# Note that the config below will result in interfaces being configured as "no switchport", without an IP address.
# This makes it possible to only forward PTP packets and nothing more.
#
# Expected config:
#
# interface Ethernet6
#    description P2P_LINK_TO_ptp-tests-spine2_Ethernet6
#    no shutdown
#    mtu 9000
#    no switchport
#    ptp enable
#    ptp sync-message interval -3
#    ptp announce interval 0
#    ptp transport ipv4
#    ptp announce timeout 3
#    ptp delay-req interval -3
#
core_interfaces:
  p2p_links:
    - id: 1
      nodes: [ ptp-tests-spine1, ptp-tests-spine2 ]
      interfaces: [ Ethernet6, Ethernet6 ]
      ptp_enable: true
      include_in_underlay_protocol: false
    - id: 2
      nodes: [ ptp-tests-spine1, ptp-tests-spine2 ]
      interfaces: [ Ethernet7, Ethernet7 ]
      ptp_enable: true
      include_in_underlay_protocol: false

tenants:
  PTP:
    mac_vrf_vni_base: 10000
    vrfs:
      # VRF definitions inside the tenant.
      VRF1:
        # VRF VNI definition.
        vrf_vni: 1
        svis:
          11:
            name: VLAN11
            enabled: true
            nodes:
              ptp-tests-leaf1:
                ip_address: 172.16.11.1/24
              ptp-tests-leaf2:
                ip_address: 172.17.11.1/24

servers:
  bmca-endpoint:
    adapters:
      - type: server
        server_ports: [ eth1 ]
        switch_ports: [ Ethernet13 ]
        switches: [ ptp-tests-leaf1 ]
        vlans: 11
        mode: access
        ptp:
          enable: true
          endpoint_role: bmca

  video-endpoint:
    adapters:
      - type: server
        server_ports: [ PCI1, PCI2 ]
        switch_ports: [ Ethernet5, Ethernet5 ]
        switches: [ ptp-tests-leaf1, ptp-tests-leaf2 ]
        vlans: 11
        mode: access
        spanning_tree_portfast: edge
        ptp:
          enable: true
          endpoint_role: follower

  Endpoint-with-specific-PTP-profile:
    adapters:
      - type: server
        server_ports: [ eth3 ]
        switch_ports: [ Ethernet3 ]
        switches: [ ptp-tests-leaf1 ]
        vlans: 11
        mode: access
        ptp:
          enable: true
          profile: smpte2059-2
