---
type: media_leaf

media_leaf:
  defaults:
    platform: 7280R2
    loopback_ipv4_pool: 10.255.1.0/27
    loopback_ipv4_offset: 2
    uplink_interfaces: [ 'Ethernet49/1' ]
    uplink_switches: [ 'amber-spine1' ]
    uplink_ipv4_pool: 10.255.254.0/26
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    filter:
      tenants: [ amber ]
    ptp:
      priority2: 1

  nodes:
    amber-leaf1:
      id: 1
      bgp_as: 65101
      mgmt_ip: 10.90.227.25/24
      filter:
        tags: [ amber-leaf1 ]
      uplink_switch_interfaces:
        - Ethernet1/1

    amber-leaf2:
      id: 2
      bgp_as: 65102
      mgmt_ip: 10.90.227.27/24
      filter:
        tags: [ amber-leaf2 ]
      uplink_switch_interfaces:
        - Ethernet3/1
