---
type: leaf

leaf:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 10.254.1.0/27
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    uplink_switches: ['amber-spine1', 'amber-spine1']
    uplink_ipv4_pool: 10.254.2.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    ptp:
      dscp:
        general_messages: 46
        event_messages: 48
      monitor:
        enabled: true
        threshold:
          offset_from_master: 1234
          mean_path_delay: 4567
        missing_message:
          intervals:
            sync: 8
            follow_up: 9
            announce: 10
          sequence_ids:
            enabled: true
            announce: 11
            delay_resp: 12
            follow_up: 13
            sync: 14

  nodes:
    amber-leaf1:
      id: 1
      bgp_as: 65201
      mgmt_ip: 192.168.1.21/24
      uplink_switch_interfaces:
        - Ethernet1
        - Ethernet2

    amber-leaf2:
      id: 2
      bgp_as: 65202
      mgmt_ip: 192.168.1.22/24
      uplink_switch_interfaces:
        - Ethernet3
        - Ethernet4
