---
type: media_spine

media_spine:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 10.255.1.0/27
    bgp_as: 65100
    filter:
      tenants: [ amber ]

  nodes:
    - name: amber-spine1
      id: 1
      mgmt_ip: 172.16.1.11/24
