---
type: leaf

leaf:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 10.255.1.0/27
    uplink_interfaces: ['Ethernet51/1', 'Ethernet52/1']
    uplink_switches: ['blue-spine1', 'blue-spine1']
    uplink_ipv4_pool: 10.255.2.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    structured_config:
      router_pim_sparse_mode:
        ipv4:
          rp_addresses:
            10.255.0.1:

  nodes:
    blue-leaf1:
      id: 1
      bgp_as: 65101
      mgmt_ip: 192.168.0.21/24
      uplink_switch_interfaces:
        - Ethernet1/1
        - Ethernet1/2
    blue-leaf2:
      id: 2
      bgp_as: 65102
      mgmt_ip: 192.168.0.22/24
      uplink_switch_interfaces:
        - Ethernet1/3
        - Ethernet1/4
    blue-leaf3:
      id: 3
      bgp_as: 65103
      mgmt_ip: 192.168.0.21/24
      uplink_switch_interfaces:
        - Ethernet3/1
        - Ethernet4/1
    blue-leaf4:
      id: 4
      bgp_as: 65104
      mgmt_ip: 192.168.0.22/24
      uplink_switch_interfaces:
        - Ethernet5/1
        - Ethernet6/1
