---
type: media_leaf

media_leaf:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 10.255.2.0/27
    loopback_ipv4_offset: 1
    uplink_switches: [ 'blue-spine1', 'blue-spine1' ]
    max_parallel_uplinks: 2
    uplink_ipv4_pool: 10.255.255.0/26
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    filter:
      tenants: [ blue ]
    ptp:
      priority2: 2

  nodes:
    - name: blue-leaf1
      id: 1
      bgp_as: 65201
      mgmt_ip: 172.16.1.211/24
      filter:
        tags: [ blue-leaf1 ]

    - name: blue-leaf2
      id: 2
      bgp_as: 65202
      mgmt_ip: 172.16.1.212/24
      filter:
        tags: [ blue-leaf2 ]
