---
type: spine

spine:
  defaults:
    platform: 7280R3
    loopback_ipv4_pool: 10.252.12.0/26
    bgp_as: 65200
    structured_config:
      router_pim_sparse_mode:
        ipv4:
          rp_addresses:
            10.252.12.1:
  nodes:
    blue-spine1:
      id: 1
      mgmt_ip: 10.252.0.24/24
