---
type: leaf

leaf:
  defaults:
    loopback_ipv4_pool: 10.252.12.0/26
    loopback_ipv4_offset: 2
    uplink_interfaces: ['Ethernet49/1', 'Ethernet50/1']
    uplink_switches: ['blue-spine1', 'blue-spine1']
    uplink_ipv4_pool: 10.252.15.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    ptp:
      priority2: 2
    filter:
      tenants: [ blue ]
    structured_config:
      router_pim_sparse_mode:
        ipv4:
          rp_addresses:
            10.252.12.1:

  nodes:
    blue-leaf1:
      id: 1
      platform: 7280R2
      bgp_as: 65201
      mgmt_ip: 10.252.0.25/24
      ptp:
        priority1: 30
      filter:
        tags: [ blue-leaf1 ]
      uplink_switch_interfaces:
        - Ethernet1/1
        - Ethernet2/1
      raw_eos_cli: |
        interface Vlan121
          ip helper-address 10.252.4.253
          pim ipv4 sparse-mode

    blue-leaf2:
      id: 2
      platform: 7020R
      bgp_as: 65202
      mgmt_ip: 10.252.0.26/24
      filter:
        tags: [ blue-leaf2 ]
      uplink_interfaces: ['Ethernet49', 'Ethernet50', 'Ethernet51', 'Ethernet52']
      uplink_switches: ['blue-spine1', 'blue-spine1', 'blue-spine1', 'blue-spine1']
      uplink_interface_speed: 10g
      uplink_switch_interfaces:
        - Ethernet3/1
        - Ethernet3/2
        - Ethernet3/3
        - Ethernet3/4
      structured_config:
        static_routes:
          - vrf: default
            destination_address_prefix: 0.0.0.0/0
            gateway: 10.252.1.33
          - vrf: MGMT
            destination_address_prefix: 0.0.0.0/0
            gateway: 10.252.0.1
      raw_eos_cli: |
        interface Vlan122
          ip helper-address 10.252.4.253
          pim ipv4 sparse-mode
