---
type: spine

spine:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 10.255.0.0/27
    bgp_as: 65100
    structured_config:
      router_pim_sparse_mode:
        ipv4:
          rp_addresses:
            10.255.0.1:
  nodes:
    blue-spine1:
      id: 1
      mgmt_ip: 192.168.0.11/24
