---
# General Ansible definitions
ansible_connection: ansible.netcommon.httpapi
ansible_network_os: arista.eos.eos
# The user/password must exist on the switches
ansible_user: ansible
ansible_password: ansible
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
# Common AVD group variables
fabric_name: FABRIC
# lab local user
local_users:
  ansible:
    privilege: 15
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$43V1UjA4289H9/7r$yKimvqizvD3lVjvJFGgHNlEz2aFTkJvIl9w/vRkZUwd9ZLisYs66U138d4p13js8AgIh3HlzCaOYS4EQROCK.1
# BGP peer groups passwords
bgp_peer_groups:
  # all passwords set to "arista"
  evpn_overlay_peers:
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==
  mlag_ipv4_underlay_peer:
    password: 4b21pAdCvWeAqpcKDFMdWw==
# P2P interfaces MTU, includes VLANs 4093 and 4094 that are over peer-link
p2p_uplinks_mtu: 9214
# If you're running vEOS-lab or cEOS, you should use MTU of 1500 instead as shown in the following line
# p2p_uplinks_mtu: 1500
# Custom node_type_keys to:
# - Enable connected_endpoints on spines (for connectivity to GrandMaster)
# - Disable VTEP and MLAG on leaf switches
# - set default_ptp_priority1 for "leaf" as this is only set by default for "l3leaf"
node_type_keys:
  spine:
    type: spine
    connected_endpoints: false
    default_ptp_priority1: 20
  leaf:
    type: leaf
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 10
# Enable PTP for the entire fabric
ptp:
  enabled: true
  domain: 0
  # profile: smpte2059-2 # "Fast" profile
  # profile: aes67 # "Slow" profile
  profile: aes67-r16-2016 # used by default if no profile is specified
# Underlay multicast (SSM)
underlay_multicast: true
overlay_loopback_description: "Router-id"
custom_structured_configuration_aaa_authentication:
  login:
    default: local
custom_structured_configuration_aaa_authorization:
  exec:
    default: local
# Disable route-map for "redistribute connected"
custom_structured_configuration_router_bgp:
  redistribute_routes:
    connected:
      route_map: null
# Disable route-map and prefix-list
custom_structured_configuration_route_maps: null
custom_structured_configuration_prefix_lists: null
# P2P links between spine switches for PTP only traffic between the Amber and Blue parts of the network.
# Note that the config below will result in interfaces being configured as "no switchport", without an IP address.
# This makes it possible to only forward PTP packets and nothing more.
# core_interfaces:
#   p2p_links:
#     - id: 1
#       nodes: [ amber-spine1, blue-spine1 ]
#       interfaces: [ Ethernet6, Ethernet6 ]
#       ptp_enable: true
#       include_in_underlay_protocol: false
#     - id: 2
#       nodes: [ amber-spine1, blue-spine1 ]
#       interfaces: [ Ethernet7, Ethernet7 ]
#       ptp_enable: true
#       include_in_underlay_protocol: false
# custom_structured_configuration_hardware_counters:
#   features:
#     - multicast: ipv4
# custom_structured_configuration_tcam_profile:
#   profiles:
#     multicast-counters: "{{ lookup('file', 'tcam-profile-multicast-counters.cfg') }}"
core_interfaces:
  p2p_links:
    - id: 1
      nodes: [ amber-leaf2, fw ]
      interfaces: [ Ethernet48, ethernet1 ]
      ip: [ 10.252.1.20/28, 10.252.1.17/28 ]
      ptp_enable: false
      include_in_underlay_protocol: false
    - id: 2
      nodes: [ blue-leaf2, fw ]
      interfaces: [ Ethernet48, ethernet2 ]
      ip: [ 10.252.1.36/28, 10.252.1.33/28 ]
      ptp_enable: false
      include_in_underlay_protocol: false
    # - id: 2
    #   nodes: [ amber-spine1, blue-spine1 ]
    #   interfaces: [ Ethernet7, Ethernet7 ]
    #   ptp_enable: true
    #   include_in_underlay_protocol: false
