---
# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: admin
ansible_password: arista123!
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false

# Common AVD group variables
fabric_name: "FABRIC"

# -------------------------------------------------- VALIDATE STATE --------------------------------------------------
# configure playbook to ingnore errors and continue testing.
eos_validate_state_validation_mode_loose: true
# Format for path to r/w reports. Sync with default values configured in arista.avd.build_output_folders
root_dir: '{{ inventory_dir }}'
eos_validate_state_name: 'reports'
eos_validate_state_dir: '{{ root_dir }}/{{ eos_validate_state_name }}'
# Reports name
eos_validate_state_md_report_path: '{{ eos_validate_state_dir }}/{{ fabric_name }}-state.md'
eos_validate_state_csv_report_path: '{{ eos_validate_state_dir }}/{{ fabric_name }}-state.csv'
# Markdown flavor to support non-text rendering
# Only support default and github
validate_state_markdown_flavor: "default"
# Allow different manufacturers
accepted_xcvr_manufacturers: "{{ validation_role.xcvr_own_manufacturers | arista.avd.default(['Arastra, Inc.', 'Arista Networks']) }}"
# Allow different states for power supplies
accepted_pwr_supply_states: "{{ validation_role.pwr_supply_states | arista.avd.default(['ok']) }}"
# Allow different states for fans
accepted_fan_states: "{{ validation_role.fan_states | arista.avd.default(['ok']) }}"
# Generate MD results file
validation_report_md: "{{ validation_role.validation_report_md | arista.avd.default(true) }}"

daemon_terminattr:
  # Address of the gRPC server on CloudVision
  # TCP 9910 is used on on-prem
  # TCP 443 is used on CV as a Service
  clusters: # For multiple cluster support
    cvaas:
      cvaddrs:
        - apiserver.arista.io:443
      cvauth:
        method: token-secure
        token_file: /tmp/cv-onboarding-token
      cvvrf: MGMT
    dev:
      cvaddrs:
        - 10.243.132.193:9910
      cvauth:
        method: token
        token_file: /tmp/devtoken
      cvvrf: MGMT
    lab:
      cvaddrs:
        - 10.90.227.161:9910
      cvauth:
        method: token
        token_file: /tmp/token
      cvvrf: MGMT

# Local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$ttzoDdVO8Uz2SiBF$Ge.hQWy9wPGWyGc9.Q/mMyjycNO.9ylh40Vc.0iiqU/MtR7MKKIuOgbKkOeD3EpPMtN2SBForxog2ZCqv0kbu0
    #password: "arista123!"
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$n7NC6yuQmsXgOMKP$UZu7iLcCZgydY8NMdGAz244RVKdWqEikN.9ByPifgwQ90xS3fT6.46j5WcfUxkmVYWhWSgbIpODxVw67VkbkQ0
    #password: "arista123!"

# BGP peer groups passwords
bgp_peer_groups:
  # all passwords set to "arista"
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==

# P2P interfaces MTU, includes VLANs 4093 and 4094 that are over peer-link
p2p_uplinks_mtu: 9214
# If you're running vEOS-lab or cEOS, you should use MTU of 1500 instead as shown in the following line
# p2p_uplinks_mtu: 1500

# Custom node_type_keys to:
# - Enable connected_endpoints on spines (for connectivity to GrandMaster)
# - Disable VTEP and MLAG on leaf switches
# - Set default_ptp_priority1 for "leaf" as this is only set by default for "l3leaf"
node_type_keys:
  ptp_leaf:
    type: ptp_leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 10
  media_spine:
    type: media_spine
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 20
  media_leaf:
    type: media_leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 30

# Enable PTP for the entire fabric
ptp:
  enabled: true
  domain: 0
  profile: aes67-r16-2016 # used by default if no profile is specified
  # profile: aes67 # "Slow" profile
  # profile: smpte2059-2 # "Fast" profile

# Underlay multicast (SSM)
underlay_multicast: true
custom_structured_configuration_aaa_authentication:
  login:
    default: local
custom_structured_configuration_aaa_authorization:
  exec:
    default: local

# Disable route-map for "redistribute connected"
custom_structured_configuration_router_bgp:
  redistribute_routes:
    connected:
      route_map: null

# Disable route-map and prefix-list
custom_structured_configuration_route_maps: null
custom_structured_configuration_prefix_lists: null

core_interfaces:
  p2p_links:
    - id: 1
      # Nodes where this link should be configured
      nodes: [ media-PTP-1, media-PTP-2 ]
      # Interfaces where this link should be configured | Required unless using port-channels
      interfaces: [ Ethernet1, Ethernet1 ]
      # Enable PTP
      ptp:
        enabled: true
      # Do not add this interface to underlay routing protocol
      include_in_underlay_protocol: false
    - id: 2
      # Nodes where this link should be configured
      nodes: [ media-PTP-1, media-PTP-2 ]
      # Interfaces where this link should be configured | Required unless using port-channels
      interfaces: [ Ethernet2, Ethernet2 ]
      # Enable PTP
      ptp:
        enabled: true
      # Do not add this interface to underlay routing protocol
      include_in_underlay_protocol: false

# P2P links between spine switches for PTP only traffic between the Amber and Blue parts of the network.
# Note that the config below will result in interfaces being configured as "no switchport", without an IP address.
# This makes it possible to only forward PTP packets and nothing more.
# core_interfaces:
#   p2p_links:
#     - id: 1
#       nodes: [ amber-spine1, blue-spine1 ]
#       interfaces: [ Ethernet6, Ethernet6 ]
#       ptp_enable: true
#       include_in_underlay_protocol: false
#     - id: 2
#       nodes: [ amber-spine1, blue-spine1 ]
#       interfaces: [ Ethernet7, Ethernet7 ]
#       ptp_enable: true
#       include_in_underlay_protocol: false
# custom_structured_configuration_hardware_counters:
#   features:
#     - multicast: ipv4
# custom_structured_configuration_tcam_profile:
#   profiles:
#     multicast-counters: "{{ lookup('file', 'tcam-profile-multicast-counters.cfg') }}"

# core_interfaces:
#   p2p_links:
#     - id: 1
#       nodes: [ amber-leaf2, fw ]
#       interfaces: [ Ethernet48, ethernet1 ]
#       ip: [ 10.252.1.20/28, 10.252.1.17/28 ]
#       ptp_enable: false
#       include_in_underlay_protocol: false
#     - id: 2
#       nodes: [ blue-leaf2, fw ]
#       interfaces: [ Ethernet48, ethernet2 ]
#       ip: [ 10.252.1.36/28, 10.252.1.33/28 ]
#       ptp_enable: false
#       include_in_underlay_protocol: false
    # - id: 2
    #   nodes: [ amber-spine1, blue-spine1 ]
    #   interfaces: [ Ethernet7, Ethernet7 ]
    #   ptp_enable: true
    #   include_in_underlay_protocol: false

# # DNS Server
# name_servers:
#   - 192.168.1.1

# # NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Management VRF
# custom_structured_configuration_ntp:
#   local_interface:
#     name: Management1
#     vrf: MGMT
#   servers:
#     - name: 0.pool.ntp.org
#       vrf: MGMT

# M&E specific settings

# OOB Management network default gateway.
mgmt_interface: Management1
mgmt_gateway: 10.90.227.1
mgmt_destination_networks:
  - 0.0.0.0/0

# dns servers.
dns_domain: MnE.lab
name_servers:
  - 10.90.227.155

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp:
  servers:
    - name: ntp.aristanetworks.com
      iburst: true
      vrf: MGMT

# sFLow
sflow:
  destinations:
    127.0.0.1:
  source_interface: loopback0
  run: true

event_monitor:
  enabled: true

# Allow 3rd party transceivers on all switches
# DO NOT DISTRIBITE LICENSE OR CAPABILITY
service_unsupported_transceiver:
  license_name: FoxNetworksWoodlandsTesting
  license_key: e9ae09fb

queue_monitor_length:

queue_monitor_streaming:
  enable: true

load_interval:
  default: 5
