---
# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: ansible
ansible_password: ansible
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false

# CVaaS definitions
# cvp_instance_ip: apiserver.arista.io
# terminattr_smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
# terminattr_ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
# terminattr_disable_aaa: true

# Common AVD group variables
fabric_name: "MEDIA_FABRIC"

# Custom node_type_keys to:
# - Enable connected_endpoints on media_spines (for connectivity to endpoints if required)
# - Disable VTEP and MLAG on leaf switches
# - Set default_ptp_priority1 for "media_leaf" as this is only set by default for "l3leaf"
node_type_keys:
  - key: ptp_leaf
    type: ptp_leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 10
  - key: media_spine
    type: media_spine
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 20
  - key: media_leaf
    type: media_leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 30

# Local users
local_users:
  # Define a new user, which is called "ansible"
  - name: ansible
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true

# BGP peer groups passwords
bgp_peer_groups:
  # all passwords set to "arista"
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==

# P2P interfaces MTU, includes VLANs 4093 and 4094 that are over peer-link
# p2p_uplinks_mtu: 9214
# If you're running vEOS-lab or cEOS, you should use MTU of 1500 instead as shown in the following line
p2p_uplinks_mtu: 1500

# Set default uplink and downlink interfaces based on node type
default_interfaces:
  - types:
      - media_spine
    platforms:
      - default
    uplink_interfaces:
      - Ethernet1-2
    downlink_interfaces:
      - Ethernet1-8
  - types:
      - media_leaf
    platforms:
      - default
    uplink_interfaces:
      - Ethernet1-4
  - types:
      - ptp_leaf
    platforms:
      - default
    uplink_interfaces:
      - Ethernet1-2

daemon_terminattr:
  # Uncomment below if using CVaaS
  # cvaddrs:
  #   - apiserver.arista.io:443
  # cvauth:
  #   method: token-secure
  #   token_file: /tmp/cv-onboarding-token
  # cvvrf: MGMT
  # Below is for on-prem CVP. Comment out if using CVaaS
  cvaddrs:
    - 192.168.1.12:9910
  cvauth:
    method: token
    token_file: /tmp/token
  cvvrf: MGMT
  # Common configuration
  disable_aaa: true
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  taillogs:

# Enable PTP for the entire fabric
ptp:
  enabled: true

# Underlay multicast (SSM)
underlay_multicast: true

# Set AAA Authentication to local
aaa_authentication:
  login:
    default: local
# Set AAA Authorization to local
aaa_authorization:
  exec:
    default: local

# OOB Management network default gateway.
mgmt_interface: Management1
mgmt_gateway: 172.16.1.1
mgmt_destination_networks:
  - 0.0.0.0/0

# DNS Servers
name_servers:
  - 192.168.1.1

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
    - name: 0.pool.ntp.org
      vrf: MGMT

core_interfaces:
  p2p_links:
    - id: 1
      nodes: [ media-PTP-1, media-PTP-2 ]
      interfaces: [ Ethernet3, Ethernet3 ]
      ptp:
        enabled: true
      include_in_underlay_protocol: false
    - id: 2
      nodes: [ media-PTP-1, media-PTP-2 ]
      interfaces: [ Ethernet4, Ethernet4 ]
      ptp:
        enabled: true
      include_in_underlay_protocol: false

    # - id: 1
    #   # Nodes where this link should be configured
    #   nodes:
    #     - media-PTP-1, media-PTP-2
    #   # Interfaces where this link should be configured | Required unless using port-channels
    #   interfaces:
    #     - Ethernet3, Ethernet3
    #   # Enable PTP
    #   ptp:
    #     enabled: true
    #   # Do not add this interface to underlay routing protocol
    #   include_in_underlay_protocol: false
    # - id: 2
    #   # Nodes where this link should be configured
    #   nodes:
    #     - media-PTP-1, media-PTP-2
    #   # Interfaces where this link should be configured | Required unless using port-channels
    #   interfaces:
    #     - Ethernet4, Ethernet4
    #   # Enable PTP
    #   ptp:
    #     enabled: true
    #   # Do not add this interface to underlay routing protocol
    #   include_in_underlay_protocol: false

# -------------------------------------------------- VALIDATE STATE --------------------------------------------------
# configure playbook to ingnore errors and continue testing.
eos_validate_state_validation_mode_loose: true
# Format for path to r/w reports. Sync with default values configured in arista.avd.build_output_folders
root_dir: '{{ inventory_dir }}'
eos_validate_state_name: 'reports'
eos_validate_state_dir: '{{ root_dir }}/{{ eos_validate_state_name }}'
# Reports name
eos_validate_state_md_report_path: '{{ eos_validate_state_dir }}/{{ fabric_name }}-state.md'
eos_validate_state_csv_report_path: '{{ eos_validate_state_dir }}/{{ fabric_name }}-state.csv'
# Markdown flavor to support non-text rendering
# Only support default and github
validate_state_markdown_flavor: "default"
# Allow different manufacturers
accepted_xcvr_manufacturers: "{{ validation_role.xcvr_own_manufacturers | arista.avd.default(['Arastra, Inc.', 'Arista Networks']) }}"
# Allow different states for power supplies
accepted_pwr_supply_states: "{{ validation_role.pwr_supply_states | arista.avd.default(['ok']) }}"
# Allow different states for fans
accepted_fan_states: "{{ validation_role.fan_states | arista.avd.default(['ok']) }}"
# Generate MD results file
validation_report_md: "{{ validation_role.validation_report_md | arista.avd.default(true) }}"
