---
tenants:
  amber:
    vrfs:
      default:
        svis:
          111:
            name: VLAN111
            enabled: true
            tags: [ amber-leaf1 ]
            nodes:
              - node: amber-leaf1
                ip_address: 10.10.111.1/24
            ip_helpers:
              10.252.4.253:

          112:
            name: VLAN112
            enabled: true
            tags: [ amber-leaf2 ]
            nodes:
              - node: amber-leaf2
                ip_address: 10.10.112.1/24
            ip_helpers:
              10.252.4.253:

  blue:
    vrfs:
      default:
        svis:
          211:
            name: VLAN211
            enabled: true
            tags: [ blue-leaf1 ]
            nodes:
              - node: blue-leaf1
                ip_address: 10.10.211.1/24
          212:
            name: VLAN212
            enabled: true
            tags: [ blue-leaf2 ]
            nodes:
              - node: blue-leaf2
                ip_address: 10.10.212.1/24
  ptp:
    vrfs:
      default:
        svis:
          131:
            name: VLAN131
            enabled: true
            tags: [ media-PTP-1 ]
            nodes:
              - node: media-PTP-1
                ip_address: 10.10.131.1/24
          132:
            name: VLAN132
            enabled: true
            tags: [ media-PTP-2 ]
            nodes:
              - node: media-PTP-2
                ip_address: 10.10.132.1/24
