---
scenario:
  converge_sequence:
    - syntax
    - create
    - converge
    - verify
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
  cleanup_sequence:
    - destroy
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: dummy
    managed: false
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_extensions: 'jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n'
      gathering: explicit
  inventory:
    links:
      hosts: 'inventory/hosts.yml'
      group_vars: 'inventory/group_vars/'
      host_vars: 'inventory/host_vars/'
  ansible_args:
    - --skip-tags=documentation
  env:
    # Custom pythonpath to allow loading custom ip_addressing and descriptions modules.
    # See CUSTOM_PYTHON_MODULES_TESTS group vars for details.
    PYTHONPATH: ${PYTHONPATH}:${MOLECULE_SCENARIO_DIRECTORY}/custom_modules
verifier:
  name: ansible
